import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import destinationStyles from '../styles/Destination.module.css'
import Navbar from '../components/Navbar'
import { useState } from 'react'
import { destinations } from '../data.json'
import Image from 'next/image'
import Link from 'next/link'


const destination = () => {
  const [planets] = useState(destinations)
  const [planetIndex, setValue] = useState(0)

  const {name, images, description, distance, travel} = planets[planetIndex]

  return (
    <>
    <Head>
      <title>Destination</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>

    <div className={destinationStyles.container}>
    <Navbar/>
    <div className={destinationStyles.wrapper}>
      <div>
      <h1 className={destinationStyles.h5}><strong className={destinationStyles.strong}>01</strong> Pick Your Destination</h1>
      </div>

      <div className={destinationStyles.content}>
      <Image
      src={images.png}
      alt={name}
      width={400}
      height={400}
    />
      </div>

    <div className={destinationStyles.content}>
    <nav className={destinationStyles.nav}>
      <ul className={destinationStyles.ul}>
      {planets.map((item, index) => (
        <li className={destinationStyles.li} key={index} onClick={() =>
          setValue(index)}
          
          >
            <a className={destinationStyles.a}>{item.name}</a>
        </li>
      )

      )}
      </ul>
    </nav>

    <h2 className={styles.h2}>{name}</h2>
    <p className={destinationStyles.p}>{description}</p>
    <hr className={destinationStyles.hr}></hr>
    
    <p className={destinationStyles.sub2}>Avg. Distance</p>
    <p className={destinationStyles.sub1}>
      {distance}
    </p>
    <p className={destinationStyles.sub2}>Avg. Travel</p>
    <p className={destinationStyles.sub1}>
      {travel}
    </p>

    </div>

    </div>
  </div>
  </>
  )
}

export default destination