import Head from 'next/head'
import styles from '../styles/Layout.module.css'
import indexStyles from '../styles/Index.module.css'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={indexStyles.container}>
      <Navbar/>
      <div className={indexStyles.wrapper}>    

        <div className={indexStyles.content}>
        <h5 className={styles.h5}>
          So, you want to travel to
          </h5>
          <h1 className={styles.h1}>
            Space
          </h1>
          <p className={styles.p}>
          Let’s face it; if you want to go to space, you might as well genuinely go to 
        outer space and not hover kind of on the edge of it. Well sit back, and relax 
        because we’ll give you a truly out of this world experience!
          </p>
          </div>

          <div className={indexStyles.content}>
          <a href="#" className={indexStyles.exploreBtn}>Explore</a>
          </div>

          </div>
    </div>
    </>
  )
}
